groups/urls.py
from django.urls import path

from groups.views import get_group, GroupEditView

app_name = 'groups'

urlpatterns = [
    path('<int:id>', get_group, name='group'),
    path('update/<int:id>', GroupEditView.as_view(), name='edit_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index


urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path, include
from students.views import StudentEditView, StudentDeleteView, StudentCreateView, StudentListView

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list_students'),
    path('create', StudentCreateView.as_view(), name='create_students'),
    path('update/<int:id>', StudentEditView.as_view(), name='update_students'),
    path('delete/<int:id>', StudentDeleteView.as_view(), name='delete_students')

]

students/models.py
import datetime

from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from faker import Faker
import random


# Create your models here.
from core_lms.validators import even_integer_validator


class Student(models.Model):
    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=64, null=False)
    age = models.IntegerField(default=20, validators=[
        MinValueValidator(20),
        MaxValueValidator(120),
        even_integer_validator
    ])
    email = models.EmailField(max_length=64)
    phone_number = models.CharField(max_length=24, validators=[
        RegexValidator(
            r'^(\+\d\d?)?\(\d{3}\)(\d-?){7}$',
            message='Phone number should be in format +1(111)111-22-22'
        )
    ])
    enroll_date = models.DateField(default=datetime.datetime.today)
    graduate_date = models.DateField(default=datetime.datetime.today)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    @classmethod
    def generate_students(cls, count):
        faker = Faker()
        for i in range(count):
            s = Student()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.age = random.randint(18, 80)

            s.save()

    def __str__(self):
        return f"Student({self.id}) {self.first_name} {self.last_name} {self.age}" \
               f" {self.email} {self.phone_number} {self.enroll_date} {self.graduate_date})"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

students/models/lecture.py
from django.db import models


class Lecture(models.Model):
    name = models.CharField(max_length=32, null=False)
    students = models.ManyToManyField(
        to='students.Student',
        related_name='lectures',
        blank=True
    )

    class DifficultyLevel(models.IntegerChoices):
        LOW = 1, 'Low'
        NORMAL = 2, 'Normal'
        HIGH = 3, 'High'

    level = models.PositiveIntegerField(default=DifficultyLevel.LOW,
                                        choices=DifficultyLevel.choices)

students/models/student.py
import datetime

from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from faker import Faker
import random


# Create your models here.
from core_lms.models import Person
from core_lms.validators import even_integer_validator


class Student(Person):
    enroll_date = models.DateField(default=datetime.datetime.today)
    graduate_date = models.DateField(default=datetime.datetime.today)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    @classmethod
    def generate_students(cls, count):
        faker = Faker()
        for i in range(count):
            s = Student()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.age = random.randint(18, 80)

            s.save()

    def __str__(self):
        return f"Student({self.id}) {self.first_name} {self.last_name} {self.age}" \
               f" {self.email} {self.phone_number} {self.enroll_date} {self.graduate_date})"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

students/forms.py
import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from students.models import Student


class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = Student
        fields = {
            'first_name': ['iexact'],
            'last_name': ['iexact'],
            'age': ['exact']
        }


class StudentBaseForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean(self):
        result = super().clean()
        enroll_date = self.cleaned_data['enroll_date']
        graduate_date = self.cleaned_data['graduate_date']

        if enroll_date > graduate_date:
            raise ValidationError('Enroll date cannot be less then graduate date')

        return result

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        has_phone_number_qs = Student.objects.filter(
            phone_number=phone_number
        )
        if self.instance:
            has_phone_number_qs = has_phone_number_qs.exclude(
                id=self.instance.id
            )

        if has_phone_number_qs.exists():
            raise ValidationError('Phone number is non unique')

        return phone_number


class StudentCreateForm(StudentBaseForm):
    pass


class StudentUpdateForm(StudentBaseForm):
    class Meta:
        model = Student
        exclude = ['age']

students/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

from students.forms import StudentCreateForm, StudentUpdateForm, StudentFilter
from students.models import Student


class StudentListView(ListView):
    model = Student
    template_name = 'students/list_student.html'

    def get_filter(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return StudentFilter(data=self.request.GET, queryset=queryset)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('group__headman').order_by('-id')
        filter_ = self.get_filter(queryset)
        return filter_.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()

        paginator = Paginator(self.get_queryset(), 10)
        page_number = self.request.GET.get('page', '1')
        page_obj = paginator.page(int(page_number))
        context['page_obj'] = page_obj

        return context


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_students')
    form_class = StudentUpdateForm
    template_name = 'students/create_student.html'
    pk_url_kwarg = 'id'


class StudentEditView(UpdateView):
    model = Student
    success_url = reverse_lazy('students:list_students')
    form_class = StudentUpdateForm
    template_name = 'students/edit_student.html'
    pk_url_kwarg = 'id'


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_students')
    template_name = 'students/delete_student.html'
    pk_url_kwarg = 'id'

students/templates/students/_students_list.html
<table class="table table-striped">
    <tr>
        <th>First name</th>
        <th class="text-red border-blue">Last name</th>
        <th>Croup</th>
        <th>Headman</th>
        <th>INN</th>
        <th></th>
    </tr>
    {% for student in students %}
        <tr>
            <td>{{ student.first_name|capfirst }}</td>
            <td>{{ student.last_name|title }}</td>
            <td>
                {% if student.group_id %}
                    <a href="{% url 'groups:group' id=student.group_id %}">
                        {{ student.group.name }}
                    </a>
                {% else %}
                    <i>Empty</i>
                {% endif %}
            </td>
            <td>
                {% if student.group_id and student.group.headman_id %}
                    {{ student.group.headman.name }}
                {% endif %}
            </td>
            <td>{{ student.inn }}</td>
            <td><a href="{% url 'students:update_students' id=student.id %}">📝</a>
                <a href="{% url 'students:delete_students' id=student.id %}">🗑</a>
            </td>
        </tr>
    {% endfor %}
</table>

students/templates/students/create_student.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    <title>create_student</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{ form | crispy }}
        <p><button type='submit'>Create student</button></p>
    </form>
{% endblock %}

students/templates/students/delete_student.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    <title>edit_student</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{ form | crispy }}
        <p>Do you want to delete student {{ student.name }}?</p>
        <p>
            <button class="btn btn-danger" type='submit'>Delete</button>
            <a class="btn btn-info" href="{% url 'students:list_students' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

students/templates/students/edit_student.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>edit_student</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{ form | crispy }}
        <p><button type='submit'>Update student</button></p>
    </form>
{% endblock %}

students/templates/students/list_student.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block main %}
    <form>
        <p>Search student</p>
        {{ filter.form | crispy }}
        <p><button type='submit'>Search</button></p>
    </form>
    <br>
    <a href="{% url 'students:create_students' %}">Add new student</a>

    {% include 'students/_students_list.html' with students=page_obj.object_list %}

    {% include '_pagination.html' %}
{% endblock %}