groups/urls.py
from django.urls import path

from groups.views import get_group, GroupEditView

app_name = 'groups'

urlpatterns = [
    path('<int:id>', get_group, name='group'),
    path('update/<int:id>', GroupEditView.as_view(), name='edit_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index


urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
from teachers.views import TeacherEditView, TeacherDeleteView, TeacherCreateView, TeacherListView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list_teachers'),
    path('create', TeacherCreateView.as_view(), name='create_teachers'),
    path('update/<int:id>', TeacherEditView.as_view(), name='update_teachers'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete_teachers')

]

teachers/models.py
import datetime

from django.core.validators import MinValueValidator, RegexValidator, EmailValidator
from django.db import models
from faker import Faker
import random


# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=40, null=False)
    last_name = models.CharField(max_length=40, null=False)
    specialization = models.CharField(max_length=50, null=False)

    class CategoryLevel(models.IntegerChoices):
        TEACHER = 1, 'Teacher'
        MENTOR = 2, 'Mentor'

    category = models.PositiveIntegerField(default=CategoryLevel.TEACHER,
                                           choices=CategoryLevel.choices)

    # category = models.IntegerField(null=False)

    experience = models.IntegerField(validators=[
        MinValueValidator(3)
    ])
    email = models.EmailField(max_length=64, validators=[
        RegexValidator(
            r'^(?!.*@(\w+\.ru|mail\.net)$)',
            message='Invalid domain. Enter another email'
        )
    ])

    birth_date = models.DateField(null=True)
    phone_number = models.CharField(max_length=24)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.PROTECT,
        related_name='models'
    )

    @classmethod
    def generate_teacher(cls, count):
        faker = Faker()
        for i in range(count):
            s = Teacher()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.category = random.randint(1, 3)
            s.experience = random.randint(5, 30)

            s.save()

    def __str__(self):
        return f"Teacher({self.id} {self.first_name} {self.last_name} {self.specialization} {self.category}" \
               f" {self.experience} {self.email} {self.birth_date} {self.phone_number})"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

teachers/models/course.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=32, null=False)

teachers/models/teacher.py
import datetime
import re

from django.core.validators import MinValueValidator, RegexValidator, EmailValidator
from django.db import models
from faker import Faker
import random

# Create your models here.
from core_lms.models import Person


class Teacher(Person):
    category = models.IntegerField(null=False)
    experience = models.IntegerField(max_length=2, validators=[
        MinValueValidator(3)
    ])
    birth_date = models.DateField(null=True)
    inn = models.PositiveIntegerField(unique=True, null=True)
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.PROTECT,
        related_name='teachers'
    )
    course = models.ManyToManyField(
        to='teachers.Course',
        related_name='courses'
    )

    @classmethod
    def generate_teacher(cls, count):
        faker = Faker()
        for i in range(count):
            s = Teacher()
            s.first_name = faker.first_name()
            s.last_name = faker.last_name()
            s.category = random.randint(1, 3)
            s.experience = random.randint(5, 30)

            s.save()

    def __str__(self):
        return f"Teacher({self.id} {self.first_name} {self.last_name} {self.category}" \
               f" {self.experience} {self.email} {self.birth_date} {self.phone_number})"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

teachers/forms.py
import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from teachers.models import Teacher


class TeacherFilter(django_filters.FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'first_name': ['iexact'], 'last_name': ['iexact'],
            'experience': ['exact']
        }


class TeacherBaseForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    class Meta:
        model = Teacher
        exclude = ['birth_date']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

from core_lms.views import EditView
from teachers.models import Teacher
from teachers.forms import TeacherCreateForm, TeacherUpdateForm, TeacherFilter


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = 'teachers/list_teacher.html'

    def get_filter(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return TeacherFilter(data=self.request.GET, queryset=queryset)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('group__headman').order_by('-id')
        filter_ = self.get_filter(queryset)
        return filter_.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()

        paginator = Paginator(self.get_queryset(), 10)
        page_number = self.request.GET.get('page', '1')
        page_obj = paginator.page(int(page_number))
        context['page_obj'] = page_obj

        return context

# def get_teachers(request):
#     qs = Teacher.objects.all()
#
#     qs = qs.order_by('-id')
#     teacher_filter = TeacherFilter(data=request.GET, queryset=qs)
#     return render(request, 'teachers/list_teacher.html', {'args': request.GET, 'filter': teacher_filter})


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    success_url = reverse_lazy('teachers:list_teachers')
    form_class = TeacherUpdateForm
    template_name = 'teachers/create_teacher.html'
    pk_url_kwarg = 'id'


class TeacherEditView(LoginRequiredMixin, UpdateView):
    model = Teacher
    success_url = reverse_lazy('teachers:list_teachers')
    form_class = TeacherUpdateForm
    template_name = 'teachers/edit_teacher.html'
    pk_url_kwarg = 'id'


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list_teachers')
    template_name = 'teachers/delete_teacher.html'
    pk_url_kwarg = 'id'

teachers/templates/teachers/_teacher_list.html
<table class="table table-striped">
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Group</th>
        <th>Inn</th>
        <th></th>
    </tr>
    {% for teacher in teachers %}
        <tr>
            <td>{{ teacher.first_name|capfirst }}</td>
            <td>{{ teacher.last_name|title }}</td>
            <td>
                {% if teacher.group_id %}
                     <a href="{% url 'groups:group' id=teacher.group_id %}">
                        {{ teacher.group.name }}
                    </a>
                {% else %}
                    <i>Empty</i>
                {% endif %}
            </td>
            <td>{{ teacher.inn|title }}</td>
            <td><a href="{% url 'teachers:update_teachers' id=teacher.id %}">📝</a>
                <a href="{% url 'teachers:delete_teachers' id=teacher.id %}">🗑</a>
            </td>
        </tr>
    {% endfor %}
</table>

teachers/templates/teachers/create_teacher.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>create_teachers</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{ form | crispy }}
        <p><button type='submit'>Create teacher</button></p>
    </form>
{% endblock %}

teachers/templates/teachers/delete_teacher.html
{% extends '_base.html' %}

{% block title %}
    <title>edit_teachers</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        <p>Do you want to delete teacher {{ teacher.name }}?</p>
        <p>
            <button class="btn btn-danger" type='submit'>Delete</button>
            <a class="btn btn-info" href="{% url 'teachers:list_teachers' %}">Cancel</button></a>

        </p>
    </form>
{% endblock %}

teachers/templates/teachers/edit_teacher.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>edit_teachers</title>
{% endblock %}

{% block main %}
    <form method='post'>
        {% csrf_token %}
        {{ form | crispy }}
        <p><button type='submit'>Update teacher</button></p>
    </form>
{% endblock %}

teachers/templates/teachers/list_teacher.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block main %}
    <form>
        <p>Search teacher</p>
        {{ filter.form | crispy }}
        <p><button type='submit'>Search</button></p>
    </form>
    <br>
    <a href="{% url 'teachers:create_teachers' %}">Add new teacher</a>

    {% include 'teachers/_teacher_list.html' with teachers=page_obj.object_list %}

    {% include '_pagination.html' %}
{% endblock %}